"""added new column img_url

Revision ID: 0f06ba9c5bce
Revises: 8b332e0dfaa0
Create Date: 2026-09-18 21:29:40.650451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f06ba9c5bce'
down_revision: Union[str, Sequence[str], None] = '8b332e0dfaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('img_url', sa.String(), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'img_url')
    # ### end Alembic commands ###
